# Generated by Django 4.0.2 on 2022-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestID', models.IntegerField()),
                ('requestZip', models.IntegerField()),
                ('customerID', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('workerID', models.IntegerField()),
                ('complete', models.BooleanField(default=None)),
                ('feedBack', models.TextField()),
                ('thumbsUp', models.BooleanField(default=None)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('userZipCode', models.IntegerField()),
                ('userName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('userType', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
