# Generated by Django 4.0.2 on 2022-02-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0002_alter_user_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
