# Generated by Django 4.0.2 on 2022-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0003_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userAddress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
