# Generated by Django 4.0.2 on 2022-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0004_alter_request_workerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availablity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
