# Generated by Django 4.0.2 on 2022-03-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0004_user_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
