# Generated by Django 4.0.2 on 2022-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0005_userprofile_availablity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='availablity',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(default='', max_length=200),
        ),
    ]
