# Generated by Django 3.1.7 on 2022-03-31 15:31

from django.db import migrations

def populate_withOwner(apps, schema_editor):
    User = apps.get_model('lawndromat', 'User')
    Profile = apps.get_model('lawndromat','UserProfile')
    
    owner = User(username="owner@gmail.com",email="owner@gmail.com",password="Lawndromat!")
    profile = Profile(user=owner,userName="owner",userZipCode="84341",userAddress="someStreet",userType="owner",money=0)
    
    owner.save()
    profile.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0006_remove_userprofile_availablity_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_withOwner),
    ]
