# Generated by Django 3.2.12 on 2022-02-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawndromat', '0007_alter_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userName',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
